#!/bin/bash

echo "============================================"
echo "Textual Package Integration Guide"
echo "============================================"
echo ""
echo "To add the Textual package to your Xcode project:"
echo ""
echo "1. Open YoDaAI.xcodeproj in Xcode"
echo "2. Click on the project in the navigator (top-level 'YoDaAI')"
echo "3. Select the 'YoDaAI' project (not target)"
echo "4. Go to 'Package Dependencies' tab"
echo "5. Click the '+' button"
echo "6. Enter URL: https://github.com/gonzalezreal/textual"
echo "7. Select 'Up to Next Major Version' with '1.0.0'"
echo "8. Click 'Add Package'"
echo "9. Make sure 'Textual' is added to the 'YoDaAI' target"
echo "10. Click 'Add Package' again"
echo ""
echo "Alternatively, run this command to open Xcode:"
echo "  open YoDaAI.xcodeproj"
echo ""
echo "After adding the package, run:"
echo "  xcodebuild -scheme YoDaAI -configuration Debug build"
echo ""
